FROM dgellow/idris2:v0.1.0 as base

ARG VERSION=v0.2.0

WORKDIR /src
RUN apt-get update && apt-get -y install build-essential git clang
RUN git clone https://github.com/idris-lang/Idris2.git
WORKDIR /src/Idris2
RUN git checkout ${VERSION}
RUN export PATH="${PATH}:/root/.idris2/bin" && make all && make install

FROM ubuntu
COPY --from=base /root/.idris2 /root/.idris2
ENTRYPOINT ["/root/.idris2/bin/idris2"]
